### ISSUE TITLE
Use d3 with trireme

### ISSUE THREAD

**Issue by alex88** [apigee/trireme#130]
I'm trying to run a simple d3 script in trireme, the script actually runs fine in command line with both node and trireme:

Script: 

```
var d3 = require('d3'),
    jsdom = require('jsdom');


var createGraph = function() {
  var document = jsdom.jsdom();
  var data = [4, 8, 15, 16, 23, 42];

  var width = 420,
      barHeight = 20;

  var x = d3.scale.linear()
      .domain([0, d3.max(data)])
      .range([0, width]);

  var chart = d3.select(document.body).append('svg')
      .attr('width', width)
      .attr('height', barHeight * data.length);

  var bar = chart.selectAll('g')
      .data(data)
    .enter().append('g')
      .attr('transform', function(d, i) { return 'translate(0,' + i * barHeight + ')'; });

  bar.append('rect')
      .attr('width', x)
      .attr('height', barHeight - 1);

  bar.append('text')
      .attr('x', function(d) { return x(d) - 3; })
      .attr('y', barHeight / 2)
      .attr('dy', '.35em')
      .text(function(d) { return d; });

  return "<html><body>" + d3.select(document.body).html() + "</body></html>";
}

console.log(createGraph());
```

Console:

```
$ trireme -v
Trireme 0.8.7 node v0.10.32
$ trireme svg.js
<html><body><svg width="420" height="120"><g transform="translate(0,0)"><rect width="40" height="19"></rect><text x="37" y="10" dy=".35em">4</text></g><g transform="translate(0,20)"><rect width="80" height="19"></rect><text x="77" y="10" dy=".35em">8</text></g><g transform="translate(0,40)"><rect width="150" height="19"></rect><text x="147" y="10" dy=".35em">15</text></g><g transform="translate(0,60)"><rect width="160" height="19"></rect><text x="157" y="10" dy=".35em">16</text></g><g transform="translate(0,80)"><rect width="230.00000000000003" height="19"></rect><text x="227.00000000000003" y="10" dy=".35em">23</text></g><g transform="translate(0,100)"><rect width="420" height="19"></rect><text x="417" y="10" dy=".35em">42</text></g></svg></body></html>
$ node svg.js
<html><body><svg width="420" height="120"><g transform="translate(0,0)"><rect width="40" height="19"></rect><text x="37" y="10" dy=".35em">4</text></g><g transform="translate(0,20)"><rect width="80" height="19"></rect><text x="77" y="10" dy=".35em">8</text></g><g transform="translate(0,40)"><rect width="150" height="19"></rect><text x="147" y="10" dy=".35em">15</text></g><g transform="translate(0,60)"><rect width="160" height="19"></rect><text x="157" y="10" dy=".35em">16</text></g><g transform="translate(0,80)"><rect width="230.00000000000003" height="19"></rect><text x="227.00000000000003" y="10" dy=".35em">23</text></g><g transform="translate(0,100)"><rect width="420" height="19"></rect><text x="417" y="10" dy=".35em">42</text></g></svg></body></html>
```

Since it works from command line I thought it would work in a java project too:

```
package com.visup.svgcreator;

import io.apigee.trireme.core.*;
import org.mozilla.javascript.Function;
import org.mozilla.javascript.Scriptable;
import org.mozilla.javascript.ScriptableObject;

import java.io.File;
import java.util.concurrent.ExecutionException;

public class Runner {
    protected static ScriptFuture runningScript;
    protected static Scriptable module;
    protected static NodeEnvironment env;

    public void start() {
        System.out.println("Starting function!");
        env = new NodeEnvironment();
        try {
            startNodeModule();
        } catch (NodeException e) {
            System.err.println("Node exception in node startup: " + e.getMessage());
        } catch (InterruptedException | ExecutionException e) {
            System.err.println("Interrupt|Execution exception in node startup: " + e.getMessage());
        }
        long startTime = System.currentTimeMillis();
        System.out.println(ScriptableObject.callMethod(module, "svg", new Object[] {}).toString());
        long endTime = System.currentTimeMillis();
        System.out.println("Total execution time: " + (endTime-startTime) + "ms");
        System.out.println("Function ended!");
    }

    protected void startNodeModule()
            throws NodeException, InterruptedException, ExecutionException
    {
        ClassLoader classLoader = getClass().getClassLoader();
        File scriptFile = new File(classLoader.getResource("module.js").getFile());
        NodeScript script = env.createScript(scriptFile.getName(), scriptFile, null);
        runningScript = script.executeModule();
        module = runningScript.getModuleResult();
    }

    public void stop() {
        if (runningScript != null) {
            runningScript.cancel(true);
        }
    }
}
```

(the code is the same except the function is saved in `module.export.svg`)
however I get an exception:

```
Exception in thread "main" org.mozilla.javascript.WrappedException: Wrapped java.lang.NullPointerException (/Users/myUser/Sites/project-trireme-test/target/classes/node_modules/d3/d3.js#564)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1893)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
	at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:387)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at io.apigee.trireme.node10.node.console._c_anonymous_1(console.js:22)
	at io.apigee.trireme.node10.node.console.call(console.js)
	at io.apigee.trireme.core.modules.NativeModule$NativeImpl.runCompiledModule(NativeModule.java:213)
	at io.apigee.trireme.core.modules.NativeModule$NativeImpl.internalRequire(NativeModule.java:195)
	at io.apigee.trireme.core.modules.NativeModule$NativeImpl.require(NativeModule.java:151)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
	at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:387)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at io.apigee.trireme.node10.main.trireme._c_anonymous_16(trireme.js:233)
	at io.apigee.trireme.node10.main.trireme.call(trireme.js)
	at org.mozilla.javascript.ScriptableObject$GetterSlot.getValue(ScriptableObject.java:312)
	at org.mozilla.javascript.ScriptableObject.get(ScriptableObject.java:472)
	at org.mozilla.javascript.IdScriptableObject.get(IdScriptableObject.java:334)
	at org.mozilla.javascript.ScriptableObject.getProperty(ScriptableObject.java:2269)
	at org.mozilla.javascript.ScriptRuntime.topScopeName(ScriptRuntime.java:1947)
	at org.mozilla.javascript.ScriptRuntime.nameOrFunction(ScriptRuntime.java:1914)
	at org.mozilla.javascript.ScriptRuntime.name(ScriptRuntime.java:1856)
	at org.mozilla.javascript.gen._Users_myUser_Sites_project_trireme_test_target_classes_node_modules_jsdom_node_modules_nwmatcher_src_nwmatcher_noqsa_js_84._c_anonymous_3(/Users/myUser/Sites/project-trireme-test/target/classes/node_modules/jsdom/node_modules/nwmatcher/src/nwmatcher-noqsa.js:24)
	at org.mozilla.javascript.gen._Users_myUser_Sites_project_trireme_test_target_classes_node_modules_jsdom_node_modules_nwmatcher_src_nwmatcher_noqsa_js_84.call(/Users/myUser/Sites/project-trireme-test/target/classes/node_modules/jsdom/node_modules/nwmatcher/src/nwmatcher-noqsa.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.mozilla.javascript.gen._Users_myUser_Sites_project_trireme_test_target_classes_node_modules_jsdom_lib_jsdom_living_selectors_js_83._c_addNwmatcher_7(/Users/myUser/Sites/project-trireme-test/target/classes/node_modules/jsdom/lib/jsdom/living/selectors.js:27)
	at org.mozilla.javascript.gen._Users_myUser_Sites_project_trireme_test_target_classes_node_modules_jsdom_lib_jsdom_living_selectors_js_83.call(/Users/myUser/Sites/project-trireme-test/target/classes/node_modules/jsdom/lib/jsdom/living/selectors.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.mozilla.javascript.gen._Users_myUser_Sites_project_trireme_test_target_classes_node_modules_jsdom_lib_jsdom_living_selectors_js_83._c_anonymous_5(/Users/myUser/Sites/project-trireme-test/target/classes/node_modules/jsdom/lib/jsdom/living/selectors.js:12)
	at org.mozilla.javascript.gen._Users_myUser_Sites_project_trireme_test_target_classes_node_modules_jsdom_lib_jsdom_living_selectors_js_83.call(/Users/myUser/Sites/project-trireme-test/target/classes/node_modules/jsdom/lib/jsdom/living/selectors.js)
	at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2586)
	at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:287)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:101)
	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
	at org.mozilla.javascript.gen._Users_myUser_Sites_project_trireme_test_target_classes_node_modules_jsdom_lib_jsdom_utils_js_6._c_anonymous_11(/Users/myUser/Sites/project-trireme-test/target/classes/node_modules/jsdom/lib/jsdom/utils.js:154)
	at org.mozilla.javascript.gen._Users_myUser_Sites_project_trireme_test_target_classes_node_modules_jsdom_lib_jsdom_utils_js_6.call(/Users/myUser/Sites/project-trireme-test/target/classes/node_modules/jsdom/lib/jsdom/utils.js)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1479)
	at script(/Users/myUser/Sites/project-trireme-test/target/classes/node_modules/d3/d3.js:564)
	at script(/Users/myUser/Sites/project-trireme-test/target/classes/node_modules/d3/d3.js:620)
	at script(/Users/myUser/Sites/project-trireme-test/target/classes/node_modules/d3/d3.js:611)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.mozilla.javascript.gen._Users_myUser_Sites_project_trireme_test_target_classes_module_js_3._c_anonymous_2(/Users/myUser/Sites/project-trireme-test/target/classes/module.js:20)
	at org.mozilla.javascript.gen._Users_myUser_Sites_project_trireme_test_target_classes_module_js_3.call(/Users/myUser/Sites/project-trireme-test/target/classes/module.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:393)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3282)
	at org.mozilla.javascript.gen._Users_myUser_Sites_project_trireme_test_target_classes_module_js_3.call(/Users/myUser/Sites/project-trireme-test/target/classes/module.js)
	at org.mozilla.javascript.Context$1.run(Context.java:490)
	at org.mozilla.javascript.Context.call(Context.java:501)
	at org.mozilla.javascript.Context.call(Context.java:488)
	at org.mozilla.javascript.ScriptableObject.callMethod(ScriptableObject.java:2609)
	at org.mozilla.javascript.ScriptableObject.callMethod(ScriptableObject.java:2579)
	at com.visup.svgcreator.Runner.runWork(Runner.java:38)
	at com.visup.svgcreator.Runner.start(Runner.java:27)
	at com.visup.svgcreator.Main.main(Main.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.NullPointerException
	at io.apigee.trireme.core.modules.NativeModule$NativeImpl.require(NativeModule.java:154)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
	... 58 more
```

could be due the contextify require? If so, why it works within command line but not in the java project?

**Comment by alex88** [comment]
Looking at the exception, seems it's calling `require('util')`, I've discovered that logging the name in OptRuntime's callName function

**Comment by gbrail** [comment]
Ah, "executeModule" may be the trouble since it's not commonly used.

What are you trying to accomplish by embedding this code in Java? Do you
just need to run it inside the JVM or is some other integration needed?

It may make more sense to just call "execute" on the script, which returns
an object that you can use in order to wait for the script to exit.

On Mon, Sep 7, 2015 at 7:31 AM, Alessandro Tagliapietra <
notifications@github.com> wrote:

> Looking at the exception, seems it's calling require('util'), I've
> discovered that logging the name in OptRuntime's callName function
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apigee/trireme/issues/130#issuecomment-138313863>.
>



-- 
*Greg Brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail> @apigee <https://twitter.com/apigee>
<http://iloveapis.com/>

**Comment by alex88** [comment]
@gbrail 

1) What you mean by embedding the code in java? Have it as a string and run it? The only integration I have is to run the function with changing parameters for batch processing

2) I'm going to try with the execute method, I'll let you know

**Comment by alex88** [comment]
@gbrail how am I supposed to use that object with execute? I get

```

**Comment by gbrail** [comment]
Sorry I didn't answer this last week. There are a few things you can do.

First, the module-loading system in Node is very complicated, and Trireme doesn't try to emulate it. Instead, it runs the same code, but interfaces to the filesystem through Java.

That's a long way of saying that, right now, there's no way for the code to work unless the script and its dependencies are written to the local filesystem. That's why the "trireme" executable runs and your sample does not -- even if it works, it will eventually having trouble resolving all the dependencies in "d3" unless you put them on your filesystem. (You could just do that, of course, by having a "node_modules" directory in the working directory of the script.)

Second, if you just want to run the script and gather the output, the easiest way might just be to redirect standard output to a stream. I'll patch a sample program that does that.

Third, the problem with this approach is that every time you want to render the HTML, you'd be running the whole script, and that's going to take a long time as we compile and invoke the 1000 or so files in node_modules. A simpler way might be to put them on an HTTP server, or even deploy them as a servlet (using the servlet adapter, also in this project) if that is easier.

Hope that helps, if not let us know.

**Comment by gbrail** [comment]
Here's a sample that shows how to run a script and gather the output as a string:

```
package io.apigee.trireme.sample.d3;

import io.apigee.trireme.core.NodeEnvironment;
import io.apigee.trireme.core.NodeException;
import io.apigee.trireme.core.NodeScript;
import io.apigee.trireme.core.Sandbox;
import org.mozilla.javascript.JavaScriptException;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.nio.charset.Charset;
import java.util.concurrent.ExecutionException;

public class D3Test
{
    private static final Charset UTF8 = Charset.forName("utf8");

    public static void main(String[] args)
    {
        NodeEnvironment env = new NodeEnvironment();
        try {
            String result = runD3(env);
            System.out.println(result);

        } catch (JavaScriptException jse) {
            System.err.println(jse.getScriptStackTrace());
        } catch (Exception e) {
            e.printStackTrace(System.err);
        } finally {
            env.close();
        }
    }

    public static String runD3(NodeEnvironment env)
        throws NodeException, IOException, InterruptedException, JavaScriptException
    {
        ByteArrayOutputStream scriptOutput = new ByteArrayOutputStream();
        Sandbox sb = new Sandbox()
            .setStdout(scriptOutput)
            .setStderr(scriptOutput);
        NodeScript script = env.createScript("d3test.js", new File("./src/main/resources/d3test.js"), null);
        try {
            script.setSandbox(sb);

            try {
                script.execute().get();
            } catch (ExecutionException ee) {
                if (ee.getCause() instanceof JavaScriptException) {
                    throw (JavaScriptException)ee.getCause();
                } else {
                    throw new NodeException(ee.getCause());
                }
            }

            return new String(scriptOutput.toByteArray(), UTF8);

        } finally {
            script.close();
        }
    }
}
```

**Comment by alex88** [comment]
@gbrail yeah that's the issue, having to compile and invoke it, btw in my module example, the node script file is in the resources folder and has the node_modules folder in it.
It should work then?

**Comment by gbrail** [comment]
Well the problem you'll run into is that Trireme isn't yet smart enough to
read all the files in node_modules from inside the JAR. But if you extract
those files to the disk, then it'll find them the same way that regular
Node does. Then you can use the launcher code that I posted above to run
the script.

On Thu, Sep 17, 2015 at 1:12 AM, Alessandro Tagliapietra <
notifications@github.com> wrote:

> @gbrail <https://github.com/gbrail> yeah that's the issue, having to
> compile and invoke it, btw in my module example, the node script file is in
> the resources folder and has the node_modules folder in it.
> It should work then?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apigee/trireme/issues/130#issuecomment-140999617>.
>



-- 
*Greg Brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail> @apigee <https://twitter.com/apigee>
<http://iloveapis.com/>
