### ISSUE TITLE
A NullPointerException bug report

### ISSUE THREAD

**Issue by hyb1996** [apigee/trireme#186]
* trireme version: 0.9.1
* node version: 0.10.32, 0.12.7
* exception detail:
```
> trireme --node-version=0.10.32  npmtest.js apitest install
<apitest>: npm install []
npm WARN package.json apitest@0.0.1 No repository field.
npm WARN package.json apitest@0.0.1 No README data
Exception in thread "Trireme Async Pool" java.lang.NullPointerException
        at java.base/java.util.regex.Matcher.getTextLength(Unknown Source)
        at java.base/java.util.regex.Matcher.reset(Unknown Source)
        at java.base/java.util.regex.Matcher.<init>(Unknown Source)
        at java.base/java.util.regex.Pattern.matcher(Unknown Source)
        at io.apigee.trireme.kernel.fs.AdvancedFilesystem.getErrorCode(AdvancedFilesystem.java:614)
        at io.apigee.trireme.kernel.fs.AdvancedFilesystem.chown(AdvancedFilesystem.java:433)
        at io.apigee.trireme.node10.modules.Filesystem$FSImpl$21.execute(Filesystem.java:714)
        at io.apigee.trireme.node10.modules.Filesystem$FSImpl$1.run(Filesystem.java:147)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Exception in thread "Trireme Async Pool" java.lang.NullPointerException
        at java.base/java.util.regex.Matcher.getTextLength(Unknown Source)
        at java.base/java.util.regex.Matcher.reset(Unknown Source)
        at java.base/java.util.regex.Matcher.<init>(Unknown Source)
        at java.base/java.util.regex.Pattern.matcher(Unknown Source)
        at io.apigee.trireme.kernel.fs.AdvancedFilesystem.getErrorCode(AdvancedFilesystem.java:614)
        at io.apigee.trireme.kernel.fs.AdvancedFilesystem.chown(AdvancedFilesystem.java:433)
        at io.apigee.trireme.node10.modules.Filesystem$FSImpl$21.execute(Filesystem.java:714)
        at io.apigee.trireme.node10.modules.Filesystem$FSImpl$1.run(Filesystem.java:147)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Exception in thread "Trireme Async Pool" java.lang.NullPointerException
        at java.base/java.util.regex.Matcher.getTextLength(Unknown Source)
        at java.base/java.util.regex.Matcher.reset(Unknown Source)
```

* how to reproduce:
Create a file `npmtest.js` in trireme project directory `apptests\src\test\resources\npm` with following code:
```

var cacheDir = '.cache';
var workingDir = process.argv[2];
var command = process.argv[3];
var args = process.argv.slice(4);
process.chdir(workingDir);

console.log('<%s>: npm %s', workingDir, command, args);

var npm = require('npm');

var config = { cache: cacheDir };

npm.load(config, function(err, n) {
  if (err) {
    console.log('Error initializing NPM: %s', er);
    return;
  }

  npm.commands[command].call(this, args, function(err) {
    if (err) {
      console.log('Error running NPM: %s', err);
      setTimeout(function(){
        process.exit(2);
      }, 1000);
      throw err;
    }
  });
});
```
Then run shell command `trireme --node-version=0.10.32  npmtest.js apitest install` in this directory.

**Comment by hyb1996** [comment]
This seems to be caused by no null check.
I have created a pull request to fix it. 
https://github.com/apigee/trireme/pull/187
